# Generated by Django 3.2.8 on 2021-11-18 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_comida_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='comida',
            field=models.CharField(default='Porotos', max_length=500),
        ),
        migrations.DeleteModel(
            name='Comida',
        ),
    ]
